spring:
  application:
    name: booking-service

  graphql:
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls
    cors:
      allowed-origins: "*"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:booking-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8082

# ===== JWT =====
jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

house-service:
  url: ${HOUSE_SERVICE_URL:http://localhost:8084}

auth-service:
  url: ${AUTH_SERVICE_URL:http://localhost:8081}

kafka:
  topic:
    bookings-created: booking.created
    bookings-cancelled: booking.cancelled

kind: Application



