# Propriétés critiques pour éviter l'erreur Console.istty()
spring.output.ansi.enabled=never
spring.main.banner-mode=off
spring.devtools.restart.enabled=false
spring.docker.compose.enabled=false
java.awt.headless=true
file.encoding=UTF-8
