spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:8888

  # ===== POSTGRESQL =====
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # ===== GRAPHQL =====
  graphql:
    graphiql:
      enabled: true
    path: /graphql
    schema:
      printer:
        enabled: true

  # ===== KAFKA =====
  kafka:

    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
#      properties:
#        spring.json.add.type.headers: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:361819434983-cm1se6aefolqdhc0hashnkh6v9rg5ut6.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET:change-me}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

# ===== SERVER =====
server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR

# ===== EUREKA =====
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

# ===== JWT =====
jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

# ===== OTP =====
otp:
  expiration-minutes: 10

# ===== KAFKA TOPICS =====
kafka:
  topics:
    user-created: user.created
    user-verified: user.verified

# ===== CORS =====
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

google:
  client-id: ${GOOGLE_CLIENT_ID:}
  client-secret: ${GOOGLE_CLIENT_SECRET:}
