export const ROUTES = {
  HOME: '/',
  SEARCH: '/search',
  HOUSE_DETAIL: '/house/:id',
  HOUSE_DETAIL_LINK: (id) => `/house/${id}`,
  REVIEWS: '/reviews',
  ABOUT: '/about',
  CONTACT: '/contact',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  LOGIN: '/login',
  REGISTER: '/register',
  OTP: '/otp',
  BOOKING: '/book/:id',
  BOOKING_LINK: (id) => `/book/${id}`,
  DASHBOARD: '/dashboard',
  ADMIN: '/admin',
  MESSAGES: '/messages',
  PROFILE: '/profile',
};
