export const ROUTES = {
  HOME: '/',
  SEARCH: '/search',
  HOUSE_DETAIL: '/house/:id',
  HOUSE_DETAIL_LINK: (id) => `/house/${id}`,
  REVIEWS: '/reviews',
  ABOUT: '/about',
  CONTACT: '/contact',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  LOGIN: '/login',
  REGISTER: '/register',
  OTP: '/otp',
  BOOKING: '/book/:id',
  BOOKING_LINK: (id) => `/book/${id}`,
  DASHBOARD: '/dashboard',
  MY_BOOKINGS: '/dashboard/reservations',
  MY_HOUSES: '/dashboard/logements',
  ADD_HOUSE: '/dashboard/logements/nouveau',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/utilisateurs',
  ADMIN_HOUSES: '/admin/logements',
  ADMIN_BOOKINGS: '/admin/reservations',
  MESSAGES: '/messages',
  PROFILE: '/profile',
};
